# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caliptic < Formula
  desc "Caliptic CLI — local agent runtime and management tool for the Caliptic platform"
  homepage "https://github.com/caliptic-org/caliptic"
  version "0.1.33"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caliptic-org/releases/releases/download/v0.1.33/caliptic-cli-0.1.33-darwin-amd64.tar.gz"
      sha256 "e092047d53e25e13d9de00324ada827bf92dcee73f57755d2712540ebf09a937"

      define_method(:install) do
        bin.install "caliptic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caliptic-org/releases/releases/download/v0.1.33/caliptic-cli-0.1.33-darwin-arm64.tar.gz"
      sha256 "6ab0935f2da629775596b31e72abec0bfdb579d11bb2601d698554433a78ebb9"

      define_method(:install) do
        bin.install "caliptic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caliptic-org/releases/releases/download/v0.1.33/caliptic-cli-0.1.33-linux-amd64.tar.gz"
      sha256 "3670b1624249c581f1fccf3bb4a9520f2e9d93f2d405cd158495688a41ffba78"
      define_method(:install) do
        bin.install "caliptic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caliptic-org/releases/releases/download/v0.1.33/caliptic-cli-0.1.33-linux-arm64.tar.gz"
      sha256 "e76ac0c8ef18969bcd5d67db7d67a373b14eaf5351c1580c9d7e959d3da54ba6"
      define_method(:install) do
        bin.install "caliptic"
      end
    end
  end

  test do
    system "#{bin}/caliptic", "version"
  end
end
