# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caliptic < Formula
  desc "Caliptic CLI — local agent runtime and management tool for the Caliptic platform"
  homepage "https://github.com/caliptic-org/caliptic"
  version "0.1.23"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caliptic-org/releases/releases/download/v0.1.23/caliptic-cli-0.1.23-darwin-amd64.tar.gz"
      sha256 "c8e11b05d3b9d41ccb04a42d9715a169e42dac8b8c662ad112850e40a1e17801"

      define_method(:install) do
        bin.install "caliptic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caliptic-org/releases/releases/download/v0.1.23/caliptic-cli-0.1.23-darwin-arm64.tar.gz"
      sha256 "d7488594a9d07d594a787f235f1d9d6ea9918e675f2af9f8be910945adf7eafa"

      define_method(:install) do
        bin.install "caliptic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caliptic-org/releases/releases/download/v0.1.23/caliptic-cli-0.1.23-linux-amd64.tar.gz"
      sha256 "69c2d13be76dc327dfb11a8d7efecfdda0790267080dfc39945360f6bcb75c4d"
      define_method(:install) do
        bin.install "caliptic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caliptic-org/releases/releases/download/v0.1.23/caliptic-cli-0.1.23-linux-arm64.tar.gz"
      sha256 "210f46b526c2246454f2de929b8e92f13703d51a2b900c3cbcbe16f896055695"
      define_method(:install) do
        bin.install "caliptic"
      end
    end
  end

  test do
    system "#{bin}/caliptic", "version"
  end
end
