# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Caliptic < Formula
  desc "Caliptic CLI — local agent runtime and management tool for the Caliptic platform"
  homepage "https://github.com/caliptic-org/caliptic"
  version "0.1.36"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/caliptic-org/releases/releases/download/v0.1.36/caliptic-cli-0.1.36-darwin-amd64.tar.gz"
      sha256 "43d4ae71f2cbddcadf1b7220fd330f84056e4a71e2d9c9e32239d2b52dbc27e5"

      define_method(:install) do
        bin.install "caliptic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/caliptic-org/releases/releases/download/v0.1.36/caliptic-cli-0.1.36-darwin-arm64.tar.gz"
      sha256 "cafe5ab22ea23a42aa15ab6933c682a263c89af21320b193a34b530b91ad1302"

      define_method(:install) do
        bin.install "caliptic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/caliptic-org/releases/releases/download/v0.1.36/caliptic-cli-0.1.36-linux-amd64.tar.gz"
      sha256 "4f34cabfaea0a4df9e15c2f1148ba65282bc9324285e999d0b55c1600df21576"
      define_method(:install) do
        bin.install "caliptic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/caliptic-org/releases/releases/download/v0.1.36/caliptic-cli-0.1.36-linux-arm64.tar.gz"
      sha256 "d32a5c5a66383ad6d844aa797a8c3b61c2172cc1b03a048dcca3ce6334675c74"
      define_method(:install) do
        bin.install "caliptic"
      end
    end
  end

  test do
    system "#{bin}/caliptic", "version"
  end
end
